In [1]:
import numpy as np
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [3]:
# Load data
df = pd.read_csv(r"D:\AI\project\time_series_dataset24.csv")
df

PIN1       PTC      PDT1      PDT2      PGV1      PGV2  \
0         0.002862  0.001300  0.004675  0.004430  0.006501  0.005931   
1         0.002862  0.001297  0.004674  0.004431  0.006519  0.005950   
2         0.002862  0.001292  0.004673  0.004432  0.006524  0.005949   
3         0.002863  0.001287  0.004673  0.004432  0.006537  0.005971   
4         0.002865  0.001284  0.004673  0.004431  0.006531  0.005995   
...            ...       ...       ...       ...       ...       ...   
13823995  0.002673  0.001582  0.004092  0.003841  0.007138  0.006577   
13823996  0.002672  0.001587  0.004089  0.003838  0.007111  0.006554   
13823997  0.002671  0.001589  0.004089  0.003834  0.007081  0.006527   
13823998  0.002670  0.001585  0.004087  0.003829  0.007069  0.006505   
13823999  0.002671  0.001579  0.004087  0.003825  0.007050  0.006499   

              PGV3      PDT3      PDT4      Patm  ...  FricTorque       Pin  \
0         0.006195  0.020413  0.024108  6.285425  ...    1.246962  6.118898   
1         0.006197  0.020705  0.022757  6.291337  ...    1.250575  6.142219   
2         0.006208  0.021536  0.021985  6.287724  ...    1.245649  6.096892   
3         0.006211  0.021012  0.020271  6.283783  ...    1.266670  6.125139   
4         0.006229  0.019912  0.018715  6.288381  ...    1.247619  6.032514   
...            ...       ...       ...       ...  ...         ...       ...   
13823995  0.006932  0.021125 -0.006264  6.318599  ...    1.142187  5.881754   
13823996  0.006877  0.022708 -0.005751  6.314329  ...    1.134304  5.889965   
13823997  0.006842  0.027942 -0.002138  6.316629  ...    1.127078  5.876498   
13823998  0.006827  0.026696 -0.002301  6.320242  ...    1.135289  5.878797   
13823999  0.006802  0.024260 -0.005821  6.321884  ...    1.145143  5.872228   

             Pdiff        GV       AGV      ATB1      ATB2  Group  Stage  Head  
0         6.649683  2.636216  0.297385 -0.163528  0.224599    DPL      1    24  
1         6.677930  2.635310  0.205243 -0.051941  0.307536    DPL      1    24  
2         6.639173  2.634754  0.124694 -0.024502  0.252041    DPL      1    24  
3         6.676617  2.634428  0.108219 -0.042185  0.274605    DPL      1    24  
4         6.704535  2.634260  0.229651 -0.048283  0.203255    DPL      1    24  
...            ...       ...       ...       ...       ...    ...    ...   ...  
13823995  6.534067  4.384009  0.244296  0.208429  0.197766     FL      9    24  
13823996  6.556730  4.383941  0.122864  0.210258  0.222160     FL      9    24  
13823997  6.520928  4.383734  0.261382  0.145623  0.202035     FL      9    24  
13823998  6.571511  4.383563  0.193038  0.041963  0.208134     FL      9    24  
13823999  6.575780  4.383241  0.274807  0.105378  0.202035     FL      9    24  

[13824000 rows x 26 columns]

In [5]:
df = df.drop(['PIN1','PTC','WTmp','Head','Patm','rpm','Speed','Flow','Thrust','GenTorque','FricTorque','Pin','Pdiff','GV','AGV','Group','PDT1', 'PDT2','PDT3','PDT4'], axis= 1)
print(df)

              PGV1      PGV2      PGV3      ATB1      ATB2  Stage
0         0.006501  0.005931  0.006195 -0.163528  0.224599      1
1         0.006519  0.005950  0.006197 -0.051941  0.307536      1
2         0.006524  0.005949  0.006208 -0.024502  0.252041      1
3         0.006537  0.005971  0.006211 -0.042185  0.274605      1
4         0.006531  0.005995  0.006229 -0.048283  0.203255      1
...            ...       ...       ...       ...       ...    ...
13823995  0.007138  0.006577  0.006932  0.208429  0.197766      9
13823996  0.007111  0.006554  0.006877  0.210258  0.222160      9
13823997  0.007081  0.006527  0.006842  0.145623  0.202035      9
13823998  0.007069  0.006505  0.006827  0.041963  0.208134      9
13823999  0.007050  0.006499  0.006802  0.105378  0.202035      9

[13824000 rows x 6 columns]


In [7]:
# df_sampled = df.groupby('stage', group_keys=False).apply(
    # lambda x: x.sample(frac=0.7, random_state=42)
# ).reset_index(drop=True)

In [15]:
features = [ 'PGV1', 'PGV2', 'PGV3', 'ATB1', 'ATB2']
X = df[features].values 
y = df['Stage']-1
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [11]:
# Model
model = XGBClassifier(objective='multi:softmax', num_class=9)
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_class=9, ...)

In [13]:
# Evaluation
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%\n")
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 100.00%

Confusion Matrix:
 [[307115      0      0      0      0      0      0      0      0]
 [     0 307294      0      0      0      0      0      0      0]
 [     0      0 306750      0      0      0      0      0      0]
 [     0      0      0 306937      0      0      0      0      0]
 [     0      0      0      0 307861      0      0      0      0]
 [     0      0      0      0      0 307096      0      0      0]
 [     0      0      0      0      0      0 306837      0      0]
 [     0      0      0      0      0      0      0 308516      0]
 [     0      0      0      0      0      0      0      0 306394]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    307115
           1       1.00      1.00      1.00    307294
           2       1.00      1.00      1.00    306750
           3       1.00      1.00      1.00    306937
           4       1.00      1.00      1.00    307861
           5     